/**
 * lipuOS terminal — a virtual shell for the blog homepage.
 * Consumes /fs.json generated by scripts/terminal-fs.js and exposes the
 * whole blog as a read-only filesystem under /home/guest.
 */
(function () {
  'use strict';

  var CFG = window.__LIPU_TERM__ || {};
  var FS_URL = CFG.fs || '/fs.json';
  var HOME = ['home', 'guest'];
  var BOOT_EPOCH = new Date('2016-01-01T00:00:00').getTime();
  var HIST_KEY = 'lipu.term.history';

  /* ---------------- DOM ---------------- */
  var term = document.getElementById('lipu-term');
  if (!term) return;
  var screen = document.getElementById('term-screen');
  var outEl = document.getElementById('term-output');
  var inputEl = document.getElementById('term-input');
  var promptEl = document.getElementById('term-prompt');
  var beforeEl = document.getElementById('term-before');
  var afterEl = document.getElementById('term-after');
  var cursorEl = document.getElementById('term-cursor');

  /* ---------------- state ---------------- */
  var HOST = (location.hostname || 'lipu0324').split('.')[0];
  var DATA = null;
  var FS = null;
  var cwd = HOME.slice();
  var oldpwd = null;
  var history = [];
  var histPos = 0;
  var lastTab = 0;
  var lastFailed = false;

  /* ---------------- helpers ---------------- */
  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
  function padL(s, n) {
    s = String(s);
    while (s.length < n) s = ' ' + s;
    return s;
  }
  function scrollDown() {
    window.scrollTo(0, document.body.scrollHeight);
  }
  function print(text, cls) {
    var d = document.createElement('div');
    d.className = 't-line' + (cls ? ' ' + cls : '');
    d.textContent = text;
    outEl.appendChild(d);
    if (cls && cls.indexOf('t-err') >= 0) lastFailed = true;
  }
  function printHTML(html, cls) {
    var d = document.createElement('div');
    d.className = 't-line' + (cls ? ' ' + cls : '');
    d.innerHTML = html;
    outEl.appendChild(d);
  }
  function tokenize(s) {
    var re = /"([^"]*)"|'([^']*)'|(\S+)/g;
    var m, out = [];
    while ((m = re.exec(s))) out.push(m[1] !== undefined ? m[1] : (m[2] !== undefined ? m[2] : m[3]));
    return out;
  }

  /* ---------------- virtual filesystem ---------------- */
  function vdir(children) { return { t: 'd', c: children || {} }; }
  function vpost(p) { return { t: 'f', p: p }; }
  function vtext(text, url) { return { t: 'x', text: text, url: url || null }; }

  function fileText(node) {
    if (node.t === 'f') return node.p.title + '\n' + node.p.content;
    return node.text || '';
  }
  function fileUrl(node) {
    if (node.t === 'f') return node.p.url;
    return node.url || null;
  }
  function fileDate(node) {
    if (node.t === 'f') return node.p.date;
    return DATA ? DATA.generated : '';
  }

  function buildFS(data) {
    var guest = vdir();
    var posts = vdir(), cats = vdir(), tags = vdir(), arch = vdir();

    data.posts.forEach(function (p) {
      posts.c[p.name] = vpost(p);
      var year = (p.date || '').slice(0, 4) || 'unknown';
      (arch.c[year] || (arch.c[year] = vdir())).c[p.name] = vpost(p);
      (p.categories.length ? p.categories : ['uncategorized']).forEach(function (c) {
        (cats.c[c] || (cats.c[c] = vdir())).c[p.name] = vpost(p);
      });
      p.tags.forEach(function (t) {
        (tags.c[t] || (tags.c[t] = vdir())).c[p.name] = vpost(p);
      });
    });

    guest.c['posts'] = posts;
    guest.c['categories'] = cats;
    guest.c['tags'] = tags;
    guest.c['archives'] = arch;
    if (data.about) guest.c['about.md'] = vtext(data.about.content, data.about.url);
    guest.c['README.md'] = vtext(readmeText(data));
    guest.c['.secret'] = vtext(secretText(data));

    var home = vdir({ guest: guest });
    return vdir({ home: home });
  }

  function readmeText(data) {
    return [
      '# ' + data.site.title,
      '',
      data.site.subtitle || '',
      data.site.description || '',
      '',
      '## 目录结构',
      '  posts/        全部文章（' + data.posts.length + ' 篇 .md）',
      '  categories/   按分类浏览',
      '  tags/         按标签浏览',
      '  archives/     按年份浏览',
      '  about.md      关于站长',
      '',
      '## 小贴士',
      '  · Tab 补全命令和路径，↑/↓ 翻阅历史，Ctrl+L 清屏',
      '  · grep -i <关键词> posts/   全文搜索',
      '  · less posts/<文章.md>      分页器跳转到文章页阅读',
      '  · 文章列表也可以直接点击（ls 输出的文件名是链接）'
    ].join('\n');
  }

  function secretText(data) {
    return [
      '你找到了隐藏文件。',
      '',
      '这里没有宝藏，只有一句格言：',
      '“Keep calm and pull the reset low.”',
      '',
      '—— ' + (data.site.author || 'lipu0324')
    ].join('\n');
  }

  /* ---------------- path resolution ---------------- */
  function splitPath(p) {
    return p.split('/').filter(function (x) { return x.length > 0; });
  }
  function resolveParts(p) {
    var base;
    if (p.charAt(0) === '~') {
      base = HOME.slice();
      p = p.slice(1);
      if (p.charAt(0) === '/') p = p.slice(1);
    } else if (p.charAt(0) === '/') {
      base = [];
    } else {
      base = cwd.slice();
    }
    var segs = base.concat(splitPath(p));
    var out = [];
    for (var i = 0; i < segs.length; i++) {
      var s = segs[i];
      if (s === '.') continue;
      if (s === '..') { if (out.length) out.pop(); continue; }
      out.push(s);
    }
    return out;
  }
  function nodeAt(parts) {
    var n = FS;
    for (var i = 0; i < parts.length; i++) {
      if (!n || n.t !== 'd') return null;
      n = n.c[parts[i]];
    }
    return n || null;
  }
  function displayPath(parts) {
    if (parts.length >= HOME.length &&
        parts[0] === HOME[0] && parts[1] === HOME[1]) {
      var rest = parts.slice(HOME.length);
      return '~' + (rest.length ? '/' + rest.join('/') : '');
    }
    return '/' + parts.join('/');
  }
  function relPath(parts) {
    for (var i = 0; i < cwd.length; i++) {
      if (parts[i] !== cwd[i]) return displayPath(parts);
    }
    if (parts.length === cwd.length) return '.';
    return parts.slice(cwd.length).join('/');
  }
  function collectFiles(node, parts, arr) {
    Object.keys(node.c).sort().forEach(function (name) {
      var child = node.c[name];
      var p = parts.concat(name);
      if (child.t === 'd') collectFiles(child, p, arr);
      else arr.push({ parts: p, node: child });
    });
  }

  /* ---------------- prompt & input rendering ---------------- */
  function promptHTML() {
    return '<span class="p-arrow' + (lastFailed ? ' fail' : '') + '">➜</span>  ' +
           '<span class="p-path">' + esc(displayPath(cwd)) + '</span> ' +
           '<span class="p-git">git:(</span><span class="p-branch">main</span><span class="p-git">)</span> ';
  }
  function renderPrompt() {
    promptEl.innerHTML = promptHTML();
  }
  function echoLine(cmdText) {
    printHTML('<span class="t-echo">' + promptHTML() + esc(cmdText) + '</span>');
  }
  function renderInput() {
    var v = inputEl.value;
    var pos = inputEl.selectionStart == null ? v.length : inputEl.selectionStart;
    beforeEl.textContent = v.slice(0, pos);
    var ch = v.charAt(pos);
    cursorEl.textContent = ch || ' ';
    cursorEl.classList.toggle('idle', !ch);
    afterEl.textContent = ch ? v.slice(pos + 1) : '';
  }

  /* ---------------- history ---------------- */
  function loadHistory() {
    try {
      var raw = localStorage.getItem(HIST_KEY);
      if (raw) history = JSON.parse(raw) || [];
    } catch (e) { history = []; }
    histPos = history.length;
  }
  function pushHistory(cmd) {
    if (!cmd || history[history.length - 1] === cmd) { histPos = history.length; return; }
    history.push(cmd);
    if (history.length > 200) history = history.slice(-200);
    histPos = history.length;
    try { localStorage.setItem(HIST_KEY, JSON.stringify(history)); } catch (e) { /* ignore */ }
  }
  function histMove(dir) {
    if (!history.length) return;
    if (dir < 0 && histPos > 0) histPos--;
    else if (dir > 0 && histPos < history.length) histPos++;
    else return;
    inputEl.value = history[histPos] || '';
    inputEl.selectionStart = inputEl.selectionEnd = inputEl.value.length;
    renderInput();
  }

  /* ---------------- commands ---------------- */
  function cmdHelp(args) {
    if (args[0]) {
      var name = ALIASES[args[0]] ? ALIASES[args[0]][0] : args[0];
      var c = COMMANDS[name];
      if (!c) { print('help: 没有 ' + args[0] + ' 的帮助条目', 't-err'); return; }
      print('用法: ' + c.usage);
      print('      ' + c.desc);
      return;
    }
    print([
      'lipuOS guest shell — 可用指令：',
      '',
      '  浏览',
      '    ls [-la] [路径]        列出目录内容（文件名可直接点击）',
      '    cd [路径]              切换目录，cd - 返回上一个目录',
      '    pwd                    显示当前目录',
      '    tree [路径]            树状显示目录结构',
      '',
      '  阅读',
      '    cat <文件>             查看文件内容',
      '    less / more <文件>     分页器阅读（跳转到文章页）',
      '    head / tail [-n N] <文件>  查看开头 / 结尾 N 行',
      '    vim <文件>             跳转到文章页阅读（推荐）',
      '',
      '  搜索',
      '    grep [-ivlc] <词> [路径]   全文搜索（默认递归当前目录）',
      '    find [路径] [-name 模式]   按文件名查找，支持 * 通配',
      '',
      '  其他',
      '    help / man    history    clear    about    neofetch',
      '    date    uptime    echo    wc    which    open    exit',
      '',
      '提示：Tab 补全，↑/↓ 历史，Ctrl+C 中断，Ctrl+L 清屏。'
    ].join('\n'));
  }

  function cmdLs(args) {
    var long = false, all = false, targets = [];
    args.forEach(function (a) {
      if (a.charAt(0) === '-' && a.length > 1) {
        if (a.indexOf('l') >= 0) long = true;
        if (a.indexOf('a') >= 0) all = true;
      } else targets.push(a);
    });
    if (!targets.length) targets = ['.'];
    targets.forEach(function (t, ti) {
      var parts = resolveParts(t);
      var node = nodeAt(parts);
      if (!node) { print("ls: cannot access '" + t + "': No such file or directory", 't-err'); return; }
      if (node.t !== 'd') { printHTML(lsName(parts[parts.length - 1], node)); return; }
      if (targets.length > 1) print(t + ':');
      var names = Object.keys(node.c)
        .filter(function (n) { return all || n.charAt(0) !== '.'; })
        .sort();
      if (long) {
        names.forEach(function (n) {
          var child = node.c[n];
          var line = (child.t === 'd' ? 'drwxr-xr-x' : '-rw-r--r--') +
            ' 1 guest guest ' + padL(child.t === 'd' ? 4096 : fileText(child).length, 7) +
            ' ' + (fileDate(child) || '----------') + ' ';
          printHTML('<span class="t-dim">' + esc(line) + '</span>' + lsName(n, child));
        });
      } else {
        printHTML(names.map(function (n) { return lsName(n, node.c[n]); }).join('  '));
      }
      if (targets.length > 1 && ti < targets.length - 1) print('');
    });
  }
  function lsName(name, node) {
    if (node.t === 'd') return '<span class="t-dir">' + esc(name) + '/</span>';
    var url = fileUrl(node);
    if (url) return '<a class="t-file" href="' + esc(url) + '">' + esc(name) + '</a>';
    return '<span class="t-file">' + esc(name) + '</span>';
  }

  function cmdCd(args) {
    var t = args[0];
    if (!t || t === '~') { setCwd(HOME.slice()); return; }
    if (t === '-') {
      if (!oldpwd) { print('cd: OLDPWD not set', 't-err'); return; }
      var tmp = cwd; cwd = oldpwd; oldpwd = tmp;
      renderPrompt();
      print(displayPath(cwd));
      return;
    }
    var parts = resolveParts(t);
    var node = nodeAt(parts);
    if (!node) { print('cd: no such file or directory: ' + t, 't-err'); return; }
    if (node.t !== 'd') { print('cd: not a directory: ' + t, 't-err'); return; }
    setCwd(parts);
  }
  function setCwd(parts) {
    oldpwd = cwd;
    cwd = parts;
    renderPrompt();
  }

  function cmdPwd() { print(displayPath(cwd)); }

  function cmdCat(args) {
    if (!args.length) { print('cat: 缺少文件参数', 't-err'); return; }
    args.forEach(function (a) {
      var node = nodeAt(resolveParts(a));
      if (!node) { print('cat: ' + a + ': No such file or directory', 't-err'); return; }
      if (node.t === 'd') { print('cat: ' + a + ': Is a directory', 't-err'); return; }
      print(fileText(node));
    });
  }

  function cmdHeadTail(args, isHead, name) {
    var n = 10, files = [];
    for (var i = 0; i < args.length; i++) {
      var a = args[i];
      if (a === '-n') { n = parseInt(args[++i], 10) || 10; }
      else if (/^-\d+$/.test(a)) n = parseInt(a.slice(1), 10);
      else files.push(a);
    }
    if (!files.length) { print(name + ': 缺少文件参数', 't-err'); return; }
    files.forEach(function (f) {
      var node = nodeAt(resolveParts(f));
      if (!node) { print(name + ': ' + f + ': No such file or directory', 't-err'); return; }
      if (node.t === 'd') { print(name + ': ' + f + ': Is a directory', 't-err'); return; }
      var lines = fileText(node).split('\n');
      print((isHead ? lines.slice(0, n) : lines.slice(-n)).join('\n'));
    });
  }

  function cmdWc(args) {
    var onlyLines = false, files = [];
    args.forEach(function (a) {
      if (a === '-l') onlyLines = true;
      else files.push(a);
    });
    if (!files.length) { print('wc: 缺少文件参数', 't-err'); return; }
    files.forEach(function (f) {
      var node = nodeAt(resolveParts(f));
      if (!node || node.t === 'd') { print('wc: ' + f + ': No such file', 't-err'); return; }
      var text = fileText(node);
      var lines = text.split('\n').length;
      if (onlyLines) print(padL(lines, 7) + ' ' + f);
      else print(padL(lines, 7) + ' ' + padL(text.split(/\s+/).filter(Boolean).length, 7) +
                 ' ' + padL(text.length, 8) + ' ' + f);
    });
  }

  function cmdGrep(args) {
    var opt = { i: false, v: false, l: false, c: false };
    var pattern = null, paths = [];
    for (var k = 0; k < args.length; k++) {
      var a = args[k];
      if (pattern === null && a.charAt(0) === '-' && a.length > 1) {
        for (var j = 1; j < a.length; j++) {
          if ('ivlc'.indexOf(a[j]) >= 0) opt[a[j]] = true;
          else { print("grep: invalid option -- '" + a[j] + "'", 't-err'); return; }
        }
      } else if (pattern === null) pattern = a;
      else paths.push(a);
    }
    if (!pattern) { print('用法: grep [-ivlc] <关键词> [路径...]', 't-err'); return; }
    if (!paths.length) paths = ['.'];

    var entries = [];
    paths.forEach(function (p) {
      var parts = resolveParts(p);
      var node = nodeAt(parts);
      if (!node) { print('grep: ' + p + ': No such file or directory', 't-err'); return; }
      if (node.t === 'd') collectFiles(node, parts, entries);
      else entries.push({ parts: parts, node: node });
    });

    var seen = {}, uniq = [];
    entries.forEach(function (e) {
      var key = e.node.t === 'f' ? 'p:' + e.node.p.url : 'x:' + e.parts.join('/');
      if (!seen[key]) { seen[key] = 1; uniq.push(e); }
    });

    var needle = opt.i ? pattern.toLowerCase() : pattern;
    var shown = 0, MAX = 200, matchedFiles = 0;
    for (var u = 0; u < uniq.length && shown < MAX; u++) {
      var e2 = uniq[u];
      var lines = fileText(e2.node).split('\n');
      var hits = [];
      for (var li = 0; li < lines.length; li++) {
        var hay = opt.i ? lines[li].toLowerCase() : lines[li];
        var found = hay.indexOf(needle) >= 0;
        if (opt.v) found = !found;
        if (found) hits.push(li);
      }
      if (!hits.length) continue;
      matchedFiles++;
      var disp = relPath(e2.parts);
      if (opt.l) { print(disp); continue; }
      if (opt.c) { print(disp + ': ' + hits.length); continue; }
      for (var h = 0; h < hits.length && shown < MAX; h++) {
        shown++;
        var label = '<span class="t-path">' + esc(disp) + '</span>' +
          '<span class="t-dim">:</span><span class="t-ln">' + (hits[h] + 1) + '</span>' +
          '<span class="t-dim">:</span> ';
        printHTML(label + (opt.v ? esc(lines[hits[h]]) : highlightLine(lines[hits[h]], pattern, opt.i)));
      }
    }
    if (shown >= MAX) print('… 结果过多，仅显示前 ' + MAX + ' 行', 't-dim');
    else if (!matchedFiles && !opt.l && !opt.c) print('（没有匹配）试试 grep -i，或换个关键词', 't-dim');
  }
  function highlightLine(line, pattern, ci) {
    if (!pattern) return esc(line);
    var out = '', rest = line;
    var needle = ci ? pattern.toLowerCase() : pattern;
    while (rest.length) {
      var hay = ci ? rest.toLowerCase() : rest;
      var idx = hay.indexOf(needle);
      if (idx < 0) { out += esc(rest); break; }
      out += esc(rest.slice(0, idx)) + '<span class="t-hl">' + esc(rest.substr(idx, needle.length)) + '</span>';
      rest = rest.slice(idx + needle.length);
    }
    return out;
  }

  function cmdFind(args) {
    var path = '.', namePat = null, type = null, icase = false;
    for (var i = 0; i < args.length; i++) {
      var a = args[i];
      if (a === '-name') namePat = args[++i];
      else if (a === '-iname') { namePat = args[++i]; icase = true; }
      else if (a === '-type') type = args[++i];
      else if (a.charAt(0) === '-') { print('find: unknown option ' + a, 't-err'); return; }
      else path = a;
    }
    var parts = resolveParts(path);
    var node = nodeAt(parts);
    if (!node) { print("find: '" + path + "': No such file or directory", 't-err'); return; }
    var re = null;
    if (namePat) {
      re = new RegExp('^' + namePat.replace(/[.+^${}()|[\]\\]/g, '\\$&')
        .replace(/\*/g, '.*').replace(/\?/g, '.') + '$', icase ? 'i' : '');
    }
    var results = [];
    (function walk(n, p) {
      var name = p.length ? p[p.length - 1] : '/';
      var typeOk = !type || (type === 'd' ? n.t === 'd' : n.t !== 'd');
      var nameOk = !re || re.test(name);
      if (typeOk && nameOk) {
        var disp = relPath(p);
        results.push(path === '.' && disp !== '.' ? './' + disp : disp);
      }
      if (n.t === 'd') {
        Object.keys(n.c).sort().forEach(function (childName) {
          walk(n.c[childName], p.concat(childName));
        });
      }
    })(node, parts);
    print(results.join('\n'));
  }

  function cmdTree(args) {
    var path = args[0] || '.';
    var parts = resolveParts(path);
    var node = nodeAt(parts);
    if (!node) { print("tree: '" + path + "': No such file or directory", 't-err'); return; }
    if (node.t !== 'd') { print(path); return; }
    var counts = { d: 0, f: 0 };
    var lines = [path === '.' ? '.' : displayPath(parts)];
    (function rec(n, prefix) {
      var names = Object.keys(n.c).sort();
      names.forEach(function (name, idx) {
        var last = idx === names.length - 1;
        var child = n.c[name];
        lines.push(prefix + (last ? '└── ' : '├── ') + name + (child.t === 'd' ? '/' : ''));
        if (child.t === 'd') { counts.d++; rec(child, prefix + (last ? '    ' : '│   ')); }
        else counts.f++;
      });
    })(node, '');
    lines.push('');
    lines.push(counts.d + ' directories, ' + counts.f + ' files');
    print(lines.join('\n'));
  }

  function cmdOpen(args, cmdName) {
    if (!args.length) { print(cmdName + ': 缺少文件参数 — 用法: ' + cmdName + ' <文章.md>', 't-err'); return; }
    var node = nodeAt(resolveParts(args[0]));
    if (!node) { print(cmdName + ': ' + args[0] + ': No such file or directory', 't-err'); return; }
    if (node.t === 'd') { print(cmdName + ': ' + args[0] + ': Is a directory', 't-err'); return; }
    var url = fileUrl(node);
    if (!url) { print('这不是一篇文章 — 用 cat ' + args[0] + ' 直接阅读', 't-dim'); return; }
    print('Opening ' + url + ' ...');
    printHTML('<span class="t-dim">如果没有自动跳转，点击 <a href="' + esc(url) + '">' + esc(url) + '</a></span>');
    setTimeout(function () { window.location.href = url; }, 700);
  }

  function cmdNeofetch() {
    var art = [
      '    ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄',
      '  ╔═══════════════════╗',
      '  ║ ┌───────────────┐ ║',
      '  ║ │             │ ║',
      '  ║ │  LIPU-0324  │ ║',
      '  ║ │   REV 2.0   │ ║',
      '  ║ │             │ ║',
      '  ║ └───────────────┘ ║',
      '  ╚═══════════════════╝',
      '    ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄'
    ];
    var tags = {}, cats = {};
    DATA.posts.forEach(function (p) {
      p.tags.forEach(function (t) { tags[t] = 1; });
      p.categories.forEach(function (c) { cats[c] = 1; });
    });
    var days = Math.floor((Date.now() - BOOT_EPOCH) / 86400000);
    var info = [
      ['', 'guest@' + HOST],
      ['', '──────────────────'],
      ['OS', 'lipuOS 2.0.6-trm x86_64'],
      ['Host', 'GitHub Pages'],
      ['Kernel', 'hexo 7.3'],
      ['Shell', 'guest-sh 1.0'],
      ['Posts', String(DATA.posts.length)],
      ['Categories', String(Object.keys(cats).length)],
      ['Tags', String(Object.keys(tags).length)],
      ['Uptime', days + ' days'],
      ['Editor', 'Obsidian'],
      ['Theme', 'cactus / trm']
    ];
    var w = 23;
    var lines = [];
    for (var i = 0; i < Math.max(art.length, info.length); i++) {
      var a = art[i] || '';
      while (a.length < w) a += ' ';
      var inf = info[i] ? (info[i][0] ? '<span class="t-neo-k">' + esc(info[i][0]) + '</span>: ' : '') + esc(info[i][1]) : '';
      lines.push('<span class="t-neo-art">' + esc(a) + '</span>' + (inf ? ' ' + inf : ''));
    }
    printHTML(lines.join('\n'));
  }

  function cmdUptime() {
    var days = Math.floor((Date.now() - BOOT_EPOCH) / 86400000);
    var now = new Date().toTimeString().slice(0, 8);
    print(' ' + now + ' up ' + days + ' days, 1 user, load average: 0.00, 0.01, 0.05');
  }

  function cmdEcho(args) {
    var vars = {
      PWD: displayPath(cwd), HOME: '~', USER: 'guest', HOSTNAME: HOST,
      SHELL: '/bin/guest-sh', OLDPWD: oldpwd ? displayPath(oldpwd) : '', '?': '0'
    };
    var text = args.join(' ').replace(/\$(\w+|\?)/g, function (m, k) {
      return vars[k] !== undefined ? vars[k] : '';
    });
    print(text.replace(/^-n\s+/, ''));
  }

  function cmdWhich(args) {
    if (!args.length) { print('which: 缺少参数', 't-err'); return; }
    args.forEach(function (a) {
      var name = ALIASES[a] ? ALIASES[a][0] : a;
      if (COMMANDS[name]) print('/usr/bin/' + a);
      else print('no ' + a + ' in (/usr/local/bin:/usr/bin:/bin)', 't-dim');
    });
  }

  function cmdAbout() {
    if (DATA.about && DATA.about.content) {
      print(DATA.about.content.split('\n').slice(0, 12).join('\n'));
      printHTML('<span class="t-dim">完整版：<a href="' + esc(DATA.about.url) + '">' + esc(DATA.about.url) + '</a></span>');
    } else {
      print(DATA.site.description || DATA.site.title);
    }
  }

  function cmdExit() {
    print('logout');
    print('Connection to ' + HOST + ' closed.', 't-dim');
    print('（开个玩笑 — 这是个只读博客，shell 不会真的退出，继续玩）', 't-dim');
  }

  function cmdSudo(args) {
    print('guest is not in the sudoers file. This incident will be reported.', 't-err');
    print('（站长已经收到小报告了）', 't-dim');
  }

  function cmdReadonly(args, cmdName) {
    var joined = args.join(' ');
    if (cmdName === 'rm' && /-[a-z]*r/i.test(joined) && /(^|\s)\/(\s|$)/.test(joined)) {
      print('rm: it is dangerous to operate recursively on \'/\'', 't-err');
      print('（想拆站？没门）', 't-dim');
      return;
    }
    print(cmdName + ': cannot modify filesystem: Read-only file system', 't-err');
  }

  var COMMANDS = {
    help:     { fn: cmdHelp,      usage: 'help [command]',                    desc: '显示帮助信息' },
    man:      { fn: cmdHelp,      usage: 'man [command]',                     desc: '同 help' },
    ls:       { fn: cmdLs,        usage: 'ls [-la] [path]',                   desc: '列出目录内容' },
    cd:       { fn: cmdCd,        usage: 'cd [path]',                         desc: '切换目录' },
    pwd:      { fn: cmdPwd,       usage: 'pwd',                               desc: '显示当前目录' },
    tree:     { fn: cmdTree,      usage: 'tree [path]',                       desc: '树状显示目录' },
    cat:      { fn: cmdCat,       usage: 'cat <file...>',                     desc: '查看文件内容' },
    less:     { fn: function (a) { cmdOpen(a, 'less'); },  usage: 'less <file>', desc: '分页器阅读（跳转到文章页）' },
    more:     { fn: function (a) { cmdOpen(a, 'more'); },  usage: 'more <file>', desc: '同 less' },
    head:     { fn: function (a) { cmdHeadTail(a, true, 'head'); },  usage: 'head [-n N] <file>', desc: '查看文件开头' },
    tail:     { fn: function (a) { cmdHeadTail(a, false, 'tail'); }, usage: 'tail [-n N] <file>', desc: '查看文件结尾' },
    wc:       { fn: cmdWc,        usage: 'wc [-l] <file>',                    desc: '统计行数 / 词数 / 字符数' },
    grep:     { fn: cmdGrep,      usage: 'grep [-ivlc] <pattern> [path]',     desc: '全文搜索' },
    find:     { fn: cmdFind,      usage: 'find [path] [-name pat] [-type f|d]', desc: '按文件名查找' },
    vim:      { fn: function (a) { cmdOpen(a, 'vim'); },   usage: 'vim <file>',  desc: '跳转到文章页阅读' },
    open:     { fn: function (a) { cmdOpen(a, 'open'); },  usage: 'open <file>', desc: '在浏览器打开页面' },
    echo:     { fn: cmdEcho,      usage: 'echo [text]',     desc: '输出文本（支持 $PWD 等变量）' },
    clear:    { fn: function () { outEl.innerHTML = ''; }, usage: 'clear',     desc: '清空屏幕' },
    history:  { fn: function () {
                  history.forEach(function (h, i) { print(padL(i + 1, 5) + '  ' + h); });
                }, usage: 'history', desc: '查看历史指令' },
    about:    { fn: cmdAbout,     usage: 'about',           desc: '关于站长' },
    neofetch: { fn: cmdNeofetch,  usage: 'neofetch',        desc: '显示站点信息' },
    date:     { fn: function () { print(new Date().toString()); }, usage: 'date', desc: '显示当前时间' },
    uptime:   { fn: cmdUptime,    usage: 'uptime',          desc: '站点运行时间' },
    whoami:   { fn: function () { print('guest'); },        usage: 'whoami',   desc: '当前用户' },
    hostname: { fn: function () { print(HOST); },           usage: 'hostname', desc: '主机名' },
    uname:    { fn: function (a) {
                  print(a.join('').indexOf('a') >= 0
                    ? 'lipuOS ' + HOST + ' 2.0.6-trm #1 SMP PREEMPT x86_64 GNU/lipu'
                    : 'lipuOS');
                }, usage: 'uname [-a]', desc: '系统信息' },
    which:    { fn: cmdWhich,     usage: 'which <command>', desc: '查看命令位置' },
    exit:     { fn: cmdExit,      usage: 'exit',            desc: '退出（并不会）' },
    sudo:     { fn: cmdSudo,      usage: 'sudo <command>',  desc: '别想了' },
    rm:       { fn: function (a) { cmdReadonly(a, 'rm'); },    usage: 'rm <file>',  desc: '只读文件系统' },
    mkdir:    { fn: function (a) { cmdReadonly(a, 'mkdir'); }, usage: 'mkdir <dir>',  desc: '只读文件系统' },
    touch:    { fn: function (a) { cmdReadonly(a, 'touch'); }, usage: 'touch <file>', desc: '只读文件系统' },
    mv:       { fn: function (a) { cmdReadonly(a, 'mv'); },    usage: 'mv a b',     desc: '只读文件系统' },
    cp:       { fn: function (a) { cmdReadonly(a, 'cp'); },    usage: 'cp a b',     desc: '只读文件系统' },
    ping:     { fn: function (a) {
                  print('PONG ' + (a[0] || HOST) + ' — 0ms，毕竟你已经在站内了');
                }, usage: 'ping [host]', desc: '假装 ping 一下' },
    ssh:      { fn: function () { print('你已经在这个 shell 里了，不用再 ssh。'); }, usage: 'ssh', desc: '已经在这里了' }
  };

  var ALIASES = {
    ll: ['ls', '-l'], la: ['ls', '-a'], l: ['ls'],
    '..': ['cd', '..'], '...': ['cd', '../..'],
    vi: ['vim'], nvim: ['vim'], emacs: ['vim'], nano: ['vim'], view: ['vim'],
    q: ['exit'], quit: ['exit'], logout: ['exit'],
    cls: ['clear']
  };

  /* ---------------- dispatcher ---------------- */
  function run(cmd) {
    var argv = tokenize(cmd);
    if (!argv.length) return;
    lastFailed = false;
    var name = argv[0];
    if (ALIASES[name]) {
      argv = ALIASES[name].concat(argv.slice(1));
      name = argv[0];
    }
    var c = COMMANDS[name];
    if (!c) {
      print(name + ': command not found — 输入 help 查看可用指令', 't-err');
      return;
    }
    try {
      c.fn(argv.slice(1));
    } catch (err) {
      print(name + ': ' + err.message, 't-err');
    }
  }

  function submit() {
    var cmd = inputEl.value;
    echoLine(cmd);
    inputEl.value = '';
    renderInput();
    if (cmd.trim()) {
      pushHistory(cmd);
      run(cmd);
    }
    renderPrompt();
    scrollDown();
  }

  /* ---------------- tab completion ---------------- */
  function commonPrefix(list) {
    if (!list.length) return '';
    var p = list[0];
    for (var i = 1; i < list.length; i++) {
      while (list[i].indexOf(p) !== 0) p = p.slice(0, -1);
      if (!p) break;
    }
    return p;
  }
  function complete() {
    var v = inputEl.value;
    var pos = inputEl.selectionStart == null ? v.length : inputEl.selectionStart;
    var upto = v.slice(0, pos);
    var head, frag;
    if (/^\S*$/.test(upto)) { head = ''; frag = upto; }
    else {
      var lastSpace = upto.lastIndexOf(' ');
      head = upto.slice(0, lastSpace + 1);
      frag = upto.slice(lastSpace + 1);
    }
    var isCmd = head.trim() === '';
    var cands = [];
    if (isCmd) {
      cands = Object.keys(COMMANDS).concat(Object.keys(ALIASES))
        .filter(function (c) { return c.indexOf(frag) === 0; }).sort();
      applyCompletion(cands, frag, head, '');
    } else {
      var slash = frag.lastIndexOf('/');
      var dirPart = slash >= 0 ? frag.slice(0, slash + 1) : '';
      var stem = slash >= 0 ? frag.slice(slash + 1) : frag;
      var dirStr = dirPart;
      if (dirStr === '') dirStr = '.';
      else if (dirStr !== '/' && dirStr !== '~/' && /\/$/.test(dirStr)) dirStr = dirStr.slice(0, -1);
      var dirNode = nodeAt(resolveParts(dirStr));
      if (!dirNode || dirNode.t !== 'd') { lastTab = 0; return; }
      cands = Object.keys(dirNode.c)
        .filter(function (n) { return n.indexOf(stem) === 0 && (stem.charAt(0) === '.' || n.charAt(0) !== '.'); })
        .sort()
        .map(function (n) { return n + (dirNode.c[n].t === 'd' ? '/' : ''); });
      applyCompletion(cands, stem, head, dirPart);
    }
  }
  function applyCompletion(cands, stem, head, dirPart) {
    var rest = inputEl.value.slice(inputEl.selectionStart == null ? inputEl.value.length : inputEl.selectionStart);
    if (!cands.length) { lastTab = 0; return; }
    var now = Date.now();
    var dbl = now - lastTab < 700;
    lastTab = now;
    if (cands.length === 1) {
      var one = cands[0];
      var isDir = one.charAt(one.length - 1) === '/';
      var done = head + dirPart + one;
      inputEl.value = done + (isDir ? '' : ' ') + rest;
      inputEl.selectionStart = inputEl.selectionEnd = done.length + (isDir ? 0 : 1);
      renderInput();
      lastTab = 0;
      return;
    }
    var cp = commonPrefix(cands);
    if (cp.length > stem.length) {
      var done2 = head + dirPart + cp;
      inputEl.value = done2 + rest;
      inputEl.selectionStart = inputEl.selectionEnd = done2.length;
      renderInput();
    } else if (dbl) {
      echoLine(inputEl.value);
      print(cands.join('   '));
      scrollDown();
      lastTab = 0;
    }
  }

  /* ---------------- keyboard ---------------- */
  inputEl.addEventListener('keydown', function (e) {
    if (e.key === 'Enter') {
      e.preventDefault();
      submit();
    } else if (e.key === 'Tab') {
      e.preventDefault();
      complete();
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      histMove(-1);
    } else if (e.key === 'ArrowDown') {
      e.preventDefault();
      histMove(1);
    } else if (e.ctrlKey && (e.key === 'l' || e.key === 'L')) {
      e.preventDefault();
      outEl.innerHTML = '';
    } else if (e.ctrlKey && (e.key === 'c' || e.key === 'C')) {
      if (window.getSelection && String(window.getSelection()).length) return; // allow copy
      e.preventDefault();
      echoLine(inputEl.value + '^C');
      inputEl.value = '';
      renderInput();
      scrollDown();
    } else if (e.ctrlKey && (e.key === 'd' || e.key === 'D')) {
      if (!inputEl.value) {
        e.preventDefault();
        cmdExit();
        scrollDown();
      }
    }
  });
  inputEl.addEventListener('input', function () { lastTab = 0; renderInput(); });
  inputEl.addEventListener('keyup', function (e) {
    if (e.key && (e.key.indexOf('Arrow') === 0 || e.key === 'Home' || e.key === 'End' || e.key === 'Delete')) {
      renderInput();
    }
  });
  inputEl.addEventListener('click', renderInput);

  term.addEventListener('click', function (e) {
    if (e.target.tagName === 'A') return;
    if (window.getSelection && String(window.getSelection()).length) return;
    inputEl.focus();
  });

  /* ---------------- boot ---------------- */
  function boot(data) {
    var n = data.posts.length;
    print('[    0.000000] lipuOS 2.0.6-trm #1 SMP PREEMPT x86_64', 't-dim');
    print('[    0.000137] EXT4-fs (sda1): mounted filesystem with ordered data mode', 't-dim');
    print('[    0.000291] posts: ' + n + ' entries registered', 't-dim');
    print('[    0.000402] guest-sh: session opened for user guest on tty1', 't-dim');
    print('');
    print('Last login: ' + new Date().toString().replace(/ GMT.*/, '') + ' on tty1');
    print('');
    printHTML('欢迎来到 <b>' + esc(data.site.title) + '</b>' +
      (data.site.subtitle ? ' — ' + esc(data.site.subtitle) : ''));
    printHTML('<span class="t-dim">传统入口：<a href="/archives/">/archives/</a> · <a href="/about/">/about/</a> · <a href="https://github.com/lipu0324">github</a></span>');
    print('输入 help 查看全部指令。快速上手：');
    printHTML('  <span class="t-dim">$</span> ls posts/              <span class="t-dim"># 列出全部文章</span>');
    printHTML('  <span class="t-dim">$</span> grep -i cuda posts/    <span class="t-dim"># 全文搜索</span>');
    printHTML('  <span class="t-dim">$</span> less posts/&lt;Tab&gt;     <span class="t-dim"># 分页器打开文章（q 返回）</span>');
    print('');
  }

  /* ---------------- init ---------------- */
  print('booting lipuOS ...', 't-dim');
  loadHistory();
  fetch(FS_URL)
    .then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status);
      return r.json();
    })
    .then(function (data) {
      DATA = data;
      FS = buildFS(data);
      outEl.innerHTML = '';
      boot(data);
      renderPrompt();
      renderInput();
      inputEl.focus();
    })
    .catch(function (err) {
      print('kernel panic: 无法加载文件系统 (' + err.message + ')', 't-err');
      printHTML('试试传统界面：<a href="/archives/">/archives/</a>');
    });
})();
